# Site Settings
title: Evan Williams
email: evan@williams.ee
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evan.williams.ee" # the base hostname & protocol for your site
twitter_username: evan_williams
github_username:  malacandrian

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: main
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename

# Build settings
markdown: kramdown

include:
  - _sass
  - _pages
