url: http://evan.williams.ee

name: Evan Williams

description: The portfolio of Evan Williams

markdown: kramdown

permalink: /blog/:categories/

gems:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed

twitter:
    username: evan_williams

logo: /resources/images/tree.png

encoding: utf-8

timezone: Europe/London

repository: malacandrian/malacandrian.github.io
