# Site Settings
title: Evan Williams
email: evan@williams.ee
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://evan.williams.ee" # the base hostname & protocol for your site
twitter_username: evan_williams
github_username:  malacandrian

# Collecctions
collections:
  code:
    output: true
    permalink: /code/:path
  games:
    output: true
    permalink: /games/:path

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: main
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
  -
    scope:
      path: ""
      type: "code"
    values:
      image-root: /resources/images/code/
  -
    scope:
      path: ""
      type: "games"
    values:
      image-root: /resources/images/games/
  -
    scope:
      path: ""
      type: "posts"
    values:
        permalink: /blog/:slug
        image-root: /resources/images/blog/

# Build settings
markdown: kramdown

include:
  - _sass
  - _pages
